# -*- coding: utf-8 -*-
{
    'name': 'Doimoi Website',
    'summary': 'Website CMS for Doimoi Group',
    'description': """
        Quản lý nội dung động cho Website Doimoi Group (Khách hàng, Dịch vụ, Số liệu)
    """,
    'author': 'Your Company',
    'website': 'https://www.yourcompany.com',
    'category': 'Website',
    'version': '1.0',
    'depends': ['website', 'crm', 'mail'],
    'data': [
        'data/service_data.xml',
        'data/client_data.xml',
        'data/industry_data.xml',
        'data/hero_data.xml',
        'data/page_content_data.xml',
        'data/site_settings_data.xml',
        'data/project_data.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'views/backend/client_views.xml',
        'views/backend/service_group_views.xml',
        'views/backend/service_views.xml',
        'views/backend/statistic_views.xml',
        'views/backend/industry_views.xml',
        'views/backend/hero_views.xml',
        'views/backend/page_content_views.xml',
        'views/backend/site_settings_views.xml',
        'views/backend/project_views.xml',
        'views/backend/menu_views.xml',
        'views/frontend/projects.xml',
        'views/frontend/homepage.xml',
        'views/frontend/layout.xml',
        'views/frontend/components.xml',
        'views/frontend/solutions.xml',
        'views/frontend/industries.xml',
        'views/frontend/about.xml',
        'views/frontend/contact.xml',
        'views/snippets/snippets.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'dcg_website/static/src/scss/style.scss',
            'dcg_website/static/src/js/client_carousel.js',
        ],
    },
    'demo': [],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
