{
    'name': 'DCG Solution Catalog & Automatic Task Generation',
    'version': '19.0.1.0.0',
    'license': 'LGPL-3',
    'summary': 'Quản lý tập trung Danh mục Giải pháp, Module, Feature, Tài liệu, Checklist, Common Issues và Tự động sinh Task từ CRM',
    'author': 'DCG Team',
    'category': 'Services/Project',
    'images': ['static/description/icon.png'],
    'depends': [
        'project',
        'crm',
        'dcg_project_customize',
        'dcg_custom_crm',
    ],
    'data': [
        'security/solution_catalog_security.xml',
        'security/ir.model.access.csv',
        'data/solution_data.xml',
        'wizard/project_solution_change_warning_wizard_views.xml',
        'views/solution_solution_views.xml',
        'views/solution_configuration_views.xml',
        'views/solution_module_views.xml',
        'views/project_project_views.xml',
        'views/project_task_views.xml',
        'views/crm_lead_views.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': True,
}
